version: '3.5'
services:
  ui-proxy:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ui-proxy
    hostname: ui-proxy
    restart: unless-stopped
    ports:
      - 8082:8082
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf

networks:
  default:
    name: 'simple-trader'
    external: true